/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as UploadsIdRouteImport } from './routes/uploads.$id'
import { Route as ApiPublicAnalyzeImageRouteImport } from './routes/api/public/analyze-image'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicMetricsRouteImport } from './routes/api/public/metrics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsIdRoute = UploadsIdRouteImport.update({
  id: '/uploads/$id',
  path: '/uploads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyzeImageRoute = ApiPublicAnalyzeImageRouteImport.update({
  id: '/api/public/analyze-image',
  path: '/api/public/analyze-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetricsRoute = ApiPublicMetricsRouteImport.update({
  id: '/api/public/metrics',
  path: '/api/public/metrics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-docs': typeof ApiDocsRoute
  '/dashboard': typeof DashboardRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
  '/uploads/$id': typeof UploadsIdRoute
  '/api/public/analyze-image': typeof ApiPublicAnalyzeImageRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-docs': typeof ApiDocsRoute
  '/dashboard': typeof DashboardRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
  '/uploads/$id': typeof UploadsIdRoute
  '/api/public/analyze-image': typeof ApiPublicAnalyzeImageRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/api-docs': typeof ApiDocsRoute
  '/dashboard': typeof DashboardRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
  '/uploads/$id': typeof UploadsIdRoute
  '/api/public/analyze-image': typeof ApiPublicAnalyzeImageRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/api-docs'
    | '/dashboard'
    | '/health'
    | '/history'
    | '/login'
    | '/sitemap.xml'
    | '/upload'
    | '/uploads/$id'
    | '/api/public/analyze-image'
    | '/api/public/health'
    | '/api/public/metrics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/api-docs'
    | '/dashboard'
    | '/health'
    | '/history'
    | '/login'
    | '/sitemap.xml'
    | '/upload'
    | '/uploads/$id'
    | '/api/public/analyze-image'
    | '/api/public/health'
    | '/api/public/metrics'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/api-docs'
    | '/dashboard'
    | '/health'
    | '/history'
    | '/login'
    | '/sitemap.xml'
    | '/upload'
    | '/uploads/$id'
    | '/api/public/analyze-image'
    | '/api/public/health'
    | '/api/public/metrics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApiDocsRoute: typeof ApiDocsRoute
  DashboardRoute: typeof DashboardRoute
  HealthRoute: typeof HealthRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UploadRoute: typeof UploadRoute
  UploadsIdRoute: typeof UploadsIdRoute
  ApiPublicAnalyzeImageRoute: typeof ApiPublicAnalyzeImageRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicMetricsRoute: typeof ApiPublicMetricsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/$id': {
      id: '/uploads/$id'
      path: '/uploads/$id'
      fullPath: '/uploads/$id'
      preLoaderRoute: typeof UploadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analyze-image': {
      id: '/api/public/analyze-image'
      path: '/api/public/analyze-image'
      fullPath: '/api/public/analyze-image'
      preLoaderRoute: typeof ApiPublicAnalyzeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/metrics': {
      id: '/api/public/metrics'
      path: '/api/public/metrics'
      fullPath: '/api/public/metrics'
      preLoaderRoute: typeof ApiPublicMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApiDocsRoute: ApiDocsRoute,
  DashboardRoute: DashboardRoute,
  HealthRoute: HealthRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UploadRoute: UploadRoute,
  UploadsIdRoute: UploadsIdRoute,
  ApiPublicAnalyzeImageRoute: ApiPublicAnalyzeImageRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicMetricsRoute: ApiPublicMetricsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
